apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_ROOT_USERNAME: bW9uZ29hZG1pbg==  # Base64 encoded 'mongoadmin'
  MONGO_ROOT_PASSWORD: c2VjdXJlcGFzcw==  # Base64 encoded 'securepass'
